services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bookingapi_db
    environment:
      SA_PASSWORD: "MsSQLPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookingapi_api
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: >
        Server=db,1433;
        Database=BookingDb;
        User Id=sa;
        Password=MsSQLPassword123!;
        TrustServerCertificate=True
    ports:
      - "5000:80"